# Data frames #

In [1]:
import numpy as np 
import pandas as pd

##### *1. Creating a DataFrame* #####

In [2]:
# from dictionary
data ={
    "Name" : ['Ram','Shyam','Amit','Aditi','Karan','Aditya','Sonia'],
    "Age" : [25,21,36,28,48,19,20],
    "City" : ['Nagpur','Mumbai','Delhi','Panjab','UP','Bihar','Kolkata'],
    "Salary":[45000,52000,60000,49000,75000,30000,35000],
    "Performance Score":[85,79,82,87,98,92,80]
}
df = pd.DataFrame(data)
df

     Name  Age     City  Salary  Performance Score
0     Ram   25   Nagpur   45000                 85
1   Shyam   21   Mumbai   52000                 79
2    Amit   36    Delhi   60000                 82
3   Aditi   28   Panjab   49000                 87
4   Karan   48       UP   75000                 98
5  Aditya   19    Bihar   30000                 92
6   Sonia   20  Kolkata   35000                 80

In [3]:
# From datalist
data_list = [
    ['Ram',25,'Nagpur',35000],
    ['Shyam',21,'Mumbai',52000],
    ['Amit',36,'Delhi',60000],
    ['Aditya',19,'Bihar',40000],
    ['Sonia',20,'Kolkata',45000]
]
df1 = pd.DataFrame(data_list)
df1

        0   1        2      3
0     Ram  25   Nagpur  35000
1   Shyam  21   Mumbai  52000
2    Amit  36    Delhi  60000
3  Aditya  19    Bihar  40000
4   Sonia  20  Kolkata  45000

In [4]:
heading = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list,columns=heading)
df2

     Name  Age     City  Salary
0     Ram   25   Nagpur   35000
1   Shyam   21   Mumbai   52000
2    Amit   36    Delhi   60000
3  Aditya   19    Bihar   40000
4   Sonia   20  Kolkata   45000

##### *2. Selection and Indexing of Coloumns* #####

In [5]:
df

     Name  Age     City  Salary  Performance Score
0     Ram   25   Nagpur   45000                 85
1   Shyam   21   Mumbai   52000                 79
2    Amit   36    Delhi   60000                 82
3   Aditi   28   Panjab   49000                 87
4   Karan   48       UP   75000                 98
5  Aditya   19    Bihar   30000                 92
6   Sonia   20  Kolkata   35000                 80

In [6]:
df['Name']

0       Ram
1     Shyam
2      Amit
3     Aditi
4     Karan
5    Aditya
6     Sonia
Name: Name, dtype: object

In [7]:
df[['Name','Salary']]

     Name  Salary
0     Ram   45000
1   Shyam   52000
2    Amit   60000
3   Aditi   49000
4   Karan   75000
5  Aditya   30000
6   Sonia   35000

In [8]:
df1

        0   1        2      3
0     Ram  25   Nagpur  35000
1   Shyam  21   Mumbai  52000
2    Amit  36    Delhi  60000
3  Aditya  19    Bihar  40000
4   Sonia  20  Kolkata  45000

In [9]:
df1[[0,2]]

        0        2
0     Ram   Nagpur
1   Shyam   Mumbai
2    Amit    Delhi
3  Aditya    Bihar
4   Sonia  Kolkata

##### *3. Creating New Coloumns* #####

In [10]:
df2

     Name  Age     City  Salary
0     Ram   25   Nagpur   35000
1   Shyam   21   Mumbai   52000
2    Amit   36    Delhi   60000
3  Aditya   19    Bihar   40000
4   Sonia   20  Kolkata   45000

In [11]:
df2['Performance Score'] = [85,79,82,92,80]
df2

     Name  Age     City  Salary  Performance Score
0     Ram   25   Nagpur   35000                 85
1   Shyam   21   Mumbai   52000                 79
2    Amit   36    Delhi   60000                 82
3  Aditya   19    Bihar   40000                 92
4   Sonia   20  Kolkata   45000                 80

##### *4. Creating New Rows* #####

In [12]:
df2.loc[5]=['Aman',50,'UP',65000,86]
df2

     Name  Age     City  Salary  Performance Score
0     Ram   25   Nagpur   35000                 85
1   Shyam   21   Mumbai   52000                 79
2    Amit   36    Delhi   60000                 82
3  Aditya   19    Bihar   40000                 92
4   Sonia   20  Kolkata   45000                 80
5    Aman   50       UP   65000                 86

##### *5. Removing Coloumns* #####

In [13]:
df2.drop('Performance Score',axis=1)

     Name  Age     City  Salary
0     Ram   25   Nagpur   35000
1   Shyam   21   Mumbai   52000
2    Amit   36    Delhi   60000
3  Aditya   19    Bihar   40000
4   Sonia   20  Kolkata   45000
5    Aman   50       UP   65000

In [14]:
df2.drop(['Name','City'],axis=1)

   Age  Salary  Performance Score
0   25   35000                 85
1   21   52000                 79
2   36   60000                 82
3   19   40000                 92
4   20   45000                 80
5   50   65000                 86

In [15]:
df2

     Name  Age     City  Salary  Performance Score
0     Ram   25   Nagpur   35000                 85
1   Shyam   21   Mumbai   52000                 79
2    Amit   36    Delhi   60000                 82
3  Aditya   19    Bihar   40000                 92
4   Sonia   20  Kolkata   45000                 80
5    Aman   50       UP   65000                 86

In [16]:
df2.drop('Performance Score',axis=1,inplace=True)
df2

     Name  Age     City  Salary
0     Ram   25   Nagpur   35000
1   Shyam   21   Mumbai   52000
2    Amit   36    Delhi   60000
3  Aditya   19    Bihar   40000
4   Sonia   20  Kolkata   45000
5    Aman   50       UP   65000

##### *6. Removing Rows* #####

In [17]:
df2.drop(1,axis=0,inplace=True)
df2

     Name  Age     City  Salary
0     Ram   25   Nagpur   35000
2    Amit   36    Delhi   60000
3  Aditya   19    Bihar   40000
4   Sonia   20  Kolkata   45000
5    Aman   50       UP   65000

##### *7. Selecting Rows* #####

In [18]:
df2

     Name  Age     City  Salary
0     Ram   25   Nagpur   35000
2    Amit   36    Delhi   60000
3  Aditya   19    Bihar   40000
4   Sonia   20  Kolkata   45000
5    Aman   50       UP   65000

In [19]:
df2.loc[0]

Name         Ram
Age           25
City      Nagpur
Salary     35000
Name: 0, dtype: object

In [20]:
df2.loc[[2,3]]

     Name  Age   City  Salary
2    Amit   36  Delhi   60000
3  Aditya   19  Bihar   40000

In [21]:
df2.iloc[[1,3]]

    Name  Age     City  Salary
2   Amit   36    Delhi   60000
4  Sonia   20  Kolkata   45000

##### *8. Selecting Subsets of Rows and Coloumns* #####

In [22]:
df2

     Name  Age     City  Salary
0     Ram   25   Nagpur   35000
2    Amit   36    Delhi   60000
3  Aditya   19    Bihar   40000
4   Sonia   20  Kolkata   45000
5    Aman   50       UP   65000

In [23]:
df2.loc[[2,4]][['Age','City']]

   Age     City
2   36    Delhi
4   20  Kolkata

##### *9. Conditional Selection* #####

In [24]:
df2

     Name  Age     City  Salary
0     Ram   25   Nagpur   35000
2    Amit   36    Delhi   60000
3  Aditya   19    Bihar   40000
4   Sonia   20  Kolkata   45000
5    Aman   50       UP   65000

In [25]:
df2[df2['Age']>30]

   Name  Age   City  Salary
2  Amit   36  Delhi   60000
5  Aman   50     UP   65000

In [31]:
df2[(df2['Salary']<=40000) & (df2['Age']<20)]

     Name  Age   City  Salary
3  Aditya   19  Bihar   40000

In [42]:
df2[(df2['Salary']>=45000) | (df2['Age']<=20)]

     Name  Age     City  Salary
2    Amit   36    Delhi   60000
3  Aditya   19    Bihar   40000
4   Sonia   20  Kolkata   45000
5    Aman   50       UP   65000