# Missing Data #

In [1]:
import numpy as np
import pandas as pd

##### *1. Finding Missing Data* #####

In [2]:
data = {
    'A': [1,2,3,4,5],
    'B': [np.nan,2,3,4,5],
    'C': [1,2,3,np.nan,np.nan],
    'D': [1,2,np.nan,np.nan,5]
}
df = pd.DataFrame(data)
df

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  2.0
2  3  3.0  3.0  NaN
3  4  4.0  NaN  NaN
4  5  5.0  NaN  5.0

In [3]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False  False
2  False  False  False   True
3  False  False   True   True
4  False  False   True  False

In [4]:
df.isna().sum()

A    0
B    1
C    2
D    2
dtype: int64

In [5]:
df.isna().any()

A    False
B     True
C     True
D     True
dtype: bool

##### *2. Removing Missing Data* #####

In [6]:
df

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  2.0
2  3  3.0  3.0  NaN
3  4  4.0  NaN  NaN
4  5  5.0  NaN  5.0

In [7]:
df.dropna()

   A    B    C    D
1  2  2.0  2.0  2.0

In [8]:
df.dropna(thresh=3)

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  2.0
2  3  3.0  3.0  NaN
4  5  5.0  NaN  5.0

##### *3. Filling the missing data* #####

In [9]:
df

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  2.0
2  3  3.0  3.0  NaN
3  4  4.0  NaN  NaN
4  5  5.0  NaN  5.0

In [10]:
df.fillna(0)

   A    B    C    D
0  1  0.0  1.0  1.0
1  2  2.0  2.0  2.0
2  3  3.0  3.0  0.0
3  4  4.0  0.0  0.0
4  5  5.0  0.0  5.0

In [13]:
values = {'A':100,'B':0,'C':2,'D':9}
df.fillna(value=values)

   A    B    C    D
0  1  0.0  1.0  1.0
1  2  2.0  2.0  2.0
2  3  3.0  3.0  9.0
3  4  4.0  2.0  9.0
4  5  5.0  2.0  5.0

In [14]:
df.fillna(df.mean())

   A    B    C         D
0  1  3.5  1.0  1.000000
1  2  2.0  2.0  2.000000
2  3  3.0  3.0  2.666667
3  4  4.0  2.0  2.666667
4  5  5.0  2.0  5.000000