# GroupBy , Aggregation #

In [1]:
import numpy as np 
import pandas as pd

##### *1. GroupBy* #####

- sum(),mean(),max(),min()

In [2]:
data = {
'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [3]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [6]:
cat = df.groupby('Category')
for i ,v in cat :
    print(i)
    print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [5]:
# Group by 'Category' and calculate the sum of 'Sales'
df.groupby('Category')['Sales'].sum()

Category
A    570
B    930
Name: Sales, dtype: int64

In [8]:
# Group by 'Store' and calculate the mean of 'Quantity'
df.groupby('Store')['Quantity'].mean()

Store
S1    14.50
S2    16.25
Name: Quantity, dtype: float64

In [9]:
# Group by multiple columns ('Category' and 'Store') and calculate the sum of 'Sales'
df.groupby(['Category', 'Store'])['Sales'].sum()

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [ ]:
# Group by multiple columns ('Category' and 'Store') and calculate the min of 'Sales'
df.groupby(['Category', 'Store'])['Sales'].min()

Category  Store
A         S1       100
          S2       150
B         S1       200
          S2       180
Name: Sales, dtype: int64

In [11]:
# Group by 'Category' and calculate the max of 'Sales' and 'Quantity'
df.groupby('Category')[['Sales', 'Quantity']].max()

          Sales  Quantity
Category
A           200        15
B           300        25

In [13]:
# Group by 'Category' and calculate the max of 'Sales' and 'Quantity'
df.groupby('Category')[['Sales', 'Quantity']].sum()

          Sales  Quantity
Category
A           570        45
B           930        78

##### *2. Aggreration* #####

In [16]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [ ]:
df['Sales'].sum()    # sum gives the total of the 'Sales' column

np.int64(1500)

In [ ]:
df['Quantity'].mean()    # mean gives the average value of the 'Quantity' column

np.float64(15.375)

In [ ]:
df['Sales'].max()    # max gives the maximum value in the 'Sales' column

np.int64(300)

In [ ]:
df['Quantity'].min()   # min gives the minimum value in the 'Quantity' column

np.int64(8)

In [ ]:
df['Sales'].median()    # median gives the middle value of the 'Sales' column when sorted

np.float64(190.0)

In [ ]:
df['Sales'].mode()    # mode gives the most frequently occurring value in the 'Sales' column

0    200
Name: Sales, dtype: int64

In [ ]:
df['Sales'].count()   # count gives the number of non-null values in the 'Sales' column

np.int64(8)

In [ ]:
df['Sales'].std()     # std gives the number

np.float64(66.06274074155351)

In [ ]:
df['Sales'].agg(['mean','median','max','min'])  # here we cannot use mode

mean      187.5
median    190.0
max       300.0
min       100.0
Name: Sales, dtype: float64